import type { Preferences } from '../types/qbittorrent';

export type DesktopSection =
  | 'downloads'
  | 'connection'
  | 'speed'
  | 'bittorrent'
  | 'webui'
  | 'advanced'
  | 'general'
  | 'transfers'
  | 'network'
  | 'seeding'
  | 'privacy'
  | 'categories'
  | 'tags';

export type PreferenceKey = keyof Preferences;

export type PreferenceValueType<K extends PreferenceKey> = Preferences[K];

export type PreferenceValidator<K extends PreferenceKey> = (
  value: unknown
) => value is PreferenceValueType<K>;

export interface RemoteSettingMetadata<K extends PreferenceKey = PreferenceKey> {
  key: K;
  valueType: 'boolean' | 'number' | 'string' | 'record';
  validation: PreferenceValidator<K>;
  desktopSection: DesktopSection;
  min?: number;
  max?: number;
  options?: readonly { value: number }[];
  remoteOnly: boolean;
}

export const REMOTE_SETTINGS_METADATA: {
  [K in PreferenceKey]: RemoteSettingMetadata<K>;
} = {
  locale: {
    key: 'locale',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  create_subfolder_enabled: {
    key: 'create_subfolder_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  start_paused_enabled: {
    key: 'start_paused_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  auto_delete_mode: {
    key: 'auto_delete_mode',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  preallocate_all: {
    key: 'preallocate_all',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  incomplete_files_ext: {
    key: 'incomplete_files_ext',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  auto_tmm_enabled: {
    key: 'auto_tmm_enabled',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  torrent_changed_tmm_enabled: {
    key: 'torrent_changed_tmm_enabled',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  save_path_changed_tmm_enabled: {
    key: 'save_path_changed_tmm_enabled',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  category_changed_tmm_enabled: {
    key: 'category_changed_tmm_enabled',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  save_path: {
    key: 'save_path',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  temp_path_enabled: {
    key: 'temp_path_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  temp_path: {
    key: 'temp_path',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  scan_dirs: {
    key: 'scan_dirs',
    valueType: 'record',
    validation: (v): v is Record<string, number> => typeof v === 'object' && v !== null,
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  export_dir: {
    key: 'export_dir',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  export_dir_fin: {
    key: 'export_dir_fin',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  mail_notification_enabled: {
    key: 'mail_notification_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_sender: {
    key: 'mail_notification_sender',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_email: {
    key: 'mail_notification_email',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_smtp: {
    key: 'mail_notification_smtp',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_ssl_enabled: {
    key: 'mail_notification_ssl_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_auth_enabled: {
    key: 'mail_notification_auth_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_username: {
    key: 'mail_notification_username',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_password: {
    key: 'mail_notification_password',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  autorun_enabled: {
    key: 'autorun_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  autorun_program: {
    key: 'autorun_program',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  queueing_enabled: {
    key: 'queueing_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  max_active_downloads: {
    key: 'max_active_downloads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_active_torrents: {
    key: 'max_active_torrents',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_active_uploads: {
    key: 'max_active_uploads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  dont_count_slow_torrents: {
    key: 'dont_count_slow_torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  slow_torrent_dl_rate_threshold: {
    key: 'slow_torrent_dl_rate_threshold',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  slow_torrent_ul_rate_threshold: {
    key: 'slow_torrent_ul_rate_threshold',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  slow_torrent_inactive_timer: {
    key: 'slow_torrent_inactive_timer',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_ratio_enabled: {
    key: 'max_ratio_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'seeding',
    remoteOnly: true,
  },
  max_ratio: {
    key: 'max_ratio',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'seeding',
    min: 0,
    remoteOnly: true,
  },
  max_ratio_act: {
    key: 'max_ratio_act',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'seeding',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  listen_port: {
    key: 'listen_port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  upnp: {
    key: 'upnp',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  random_port: {
    key: 'random_port',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  dl_limit: {
    key: 'dl_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  up_limit: {
    key: 'up_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  alt_dl_limit: {
    key: 'alt_dl_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  alt_up_limit: {
    key: 'alt_up_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_connec: {
    key: 'max_connec',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  max_connec_per_torrent: {
    key: 'max_connec_per_torrent',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  max_uploads: {
    key: 'max_uploads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  max_uploads_per_torrent: {
    key: 'max_uploads_per_torrent',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  enable_piece_extent_affinity: {
    key: 'enable_piece_extent_affinity',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  bittorrent_protocol: {
    key: 'bittorrent_protocol',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  limit_utp_rate: {
    key: 'limit_utp_rate',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  limit_tcp_overhead: {
    key: 'limit_tcp_overhead',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  limit_lan_peers: {
    key: 'limit_lan_peers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  scheduler_enabled: {
    key: 'scheduler_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  use_alt_speed_limits: {
    key: 'use_alt_speed_limits',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  schedule_from_hour: {
    key: 'schedule_from_hour',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 23,
    remoteOnly: true,
  },
  schedule_from_min: {
    key: 'schedule_from_min',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 59,
    remoteOnly: true,
  },
  schedule_to_hour: {
    key: 'schedule_to_hour',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 23,
    remoteOnly: true,
  },
  schedule_to_min: {
    key: 'schedule_to_min',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 59,
    remoteOnly: true,
  },
  scheduler_days: {
    key: 'scheduler_days',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 7,
    remoteOnly: true,
  },
  dht: {
    key: 'dht',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  pex: {
    key: 'pex',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  lsd: {
    key: 'lsd',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  encryption: {
    key: 'encryption',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    max: 2,
    options: [
      { value: 0 },
      { value: 1 },
      { value: 2 },
    ] as const,
    remoteOnly: true,
  },
  anonymous_mode: {
    key: 'anonymous_mode',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  proxy_type: {
    key: 'proxy_type',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'connection',
    min: 0,
    max: 6,
    remoteOnly: true,
  },
  proxy_ip: {
    key: 'proxy_ip',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_port: {
    key: 'proxy_port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'connection',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  proxy_peer_connections: {
    key: 'proxy_peer_connections',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_auth_enabled: {
    key: 'proxy_auth_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_username: {
    key: 'proxy_username',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_password: {
    key: 'proxy_password',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_torrents_only: {
    key: 'proxy_torrents_only',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  ip_filter_enabled: {
    key: 'ip_filter_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  ip_filter_path: {
    key: 'ip_filter_path',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  ip_filter_trackers: {
    key: 'ip_filter_trackers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  web_ui_domain_list: {
    key: 'web_ui_domain_list',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_address: {
    key: 'web_ui_address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_port: {
    key: 'web_ui_port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  web_ui_upnp: {
    key: 'web_ui_upnp',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_username: {
    key: 'web_ui_username',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_password: {
    key: 'web_ui_password',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_csrf_protection_enabled: {
    key: 'web_ui_csrf_protection_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_clickjacking_protection_enabled: {
    key: 'web_ui_clickjacking_protection_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_secure_cookie_enabled: {
    key: 'web_ui_secure_cookie_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_max_auth_fail_count: {
    key: 'web_ui_max_auth_fail_count',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 1,
    remoteOnly: true,
  },
  web_ui_ban_duration: {
    key: 'web_ui_ban_duration',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 0,
    remoteOnly: true,
  },
  web_ui_session_timeout: {
    key: 'web_ui_session_timeout',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 0,
    remoteOnly: true,
  },
  web_ui_host_header_validation_enabled: {
    key: 'web_ui_host_header_validation_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  bypass_local_auth: {
    key: 'bypass_local_auth',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  bypass_auth_subnet_whitelist_enabled: {
    key: 'bypass_auth_subnet_whitelist_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  bypass_auth_subnet_whitelist: {
    key: 'bypass_auth_subnet_whitelist',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  alternative_webui_enabled: {
    key: 'alternative_webui_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  alternative_webui_path: {
    key: 'alternative_webui_path',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  use_https: {
    key: 'use_https',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  ssl_key: {
    key: 'ssl_key',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  ssl_cert: {
    key: 'ssl_cert',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_https_key: {
    key: 'web_ui_https_key',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_https_cert: {
    key: 'web_ui_https_cert',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  dyndns_enabled: {
    key: 'dyndns_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  dyndns_service: {
    key: 'dyndns_service',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'general',
    min: 0,
    max: 3,
    remoteOnly: true,
  },
  dyndns_username: {
    key: 'dyndns_username',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  dyndns_password: {
    key: 'dyndns_password',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  dyndns_domain: {
    key: 'dyndns_domain',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_refresh_interval: {
    key: 'rss_refresh_interval',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'general',
    min: 0,
    remoteOnly: true,
  },
  rss_max_articles_per_feed: {
    key: 'rss_max_articles_per_feed',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'general',
    min: 0,
    remoteOnly: true,
  },
  rss_processing_enabled: {
    key: 'rss_processing_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_auto_downloading_enabled: {
    key: 'rss_auto_downloading_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_download_repack_proper_episodes: {
    key: 'rss_download_repack_proper_episodes',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_smart_episode_filters: {
    key: 'rss_smart_episode_filters',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  add_trackers_enabled: {
    key: 'add_trackers_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  add_trackers: {
    key: 'add_trackers',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  web_ui_use_custom_http_headers_enabled: {
    key: 'web_ui_use_custom_http_headers_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  web_ui_custom_http_headers: {
    key: 'web_ui_custom_http_headers',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  max_seeding_time_enabled: {
    key: 'max_seeding_time_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'seeding',
    remoteOnly: true,
  },
  max_seeding_time: {
    key: 'max_seeding_time',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'seeding',
    min: 0,
    remoteOnly: true,
  },
  announce_to_all_tiers: {
    key: 'announce_to_all_tiers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  announce_to_all_trackers: {
    key: 'announce_to_all_trackers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  async_io_threads: {
    key: 'async_io_threads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    max: 32,
    remoteOnly: true,
  },
  hashing_threads: {
    key: 'hashing_threads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    max: 64,
    remoteOnly: true,
  },
  file_pool_size: {
    key: 'file_pool_size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  checking_memory_use: {
    key: 'checking_memory_use',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  disk_cache: {
    key: 'disk_cache',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  disk_cache_ttl: {
    key: 'disk_cache_ttl',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  enable_upload_suggestions: {
    key: 'enable_upload_suggestions',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  upload_suggestions_interval: {
    key: 'upload_suggestions_interval',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  send_buffer_watermark: {
    key: 'send_buffer_watermark',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  send_buffer_low_watermark: {
    key: 'send_buffer_low_watermark',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  send_buffer_watermark_factor: {
    key: 'send_buffer_watermark_factor',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  connection_speed: {
    key: 'connection_speed',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  socket_backlog_size: {
    key: 'socket_backlog_size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  outgoing_ports_min: {
    key: 'outgoing_ports_min',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    max: 65535,
    remoteOnly: true,
  },
  outgoing_ports_max: {
    key: 'outgoing_ports_max',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    max: 65535,
    remoteOnly: true,
  },
  upnp_lease_duration: {
    key: 'upnp_lease_duration',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  peer_tos: {
    key: 'peer_tos',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 6,
    remoteOnly: true,
  },
  utp_tcp_mixed_mode: {
    key: 'utp_tcp_mixed_mode',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  idn_support_enabled: {
    key: 'idn_support_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  enable_multi_connections_from_same_ip: {
    key: 'enable_multi_connections_from_same_ip',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  validate_https_tracker_certificate: {
    key: 'validate_https_tracker_certificate',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  ssrf_mitigation: {
    key: 'ssrf_mitigation',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  block_peers_on_privileged_ports: {
    key: 'block_peers_on_privileged_ports',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  enable_embedded_tracker: {
    key: 'enable_embedded_tracker',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  embedded_tracker_port: {
    key: 'embedded_tracker_port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  mark_of_the_web: {
    key: 'mark_of_the_web',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  upload_slots_behavior: {
    key: 'upload_slots_behavior',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  upload_choking_algorithm: {
    key: 'upload_choking_algorithm',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  announce_ip: {
    key: 'announce_ip',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  max_concurrent_http_announces: {
    key: 'max_concurrent_http_announces',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  stop_tracker_timeout: {
    key: 'stop_tracker_timeout',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  peer_turnover: {
    key: 'peer_turnover',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 100,
    remoteOnly: true,
  },
  peer_turnover_cutoff: {
    key: 'peer_turnover_cutoff',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 100,
    remoteOnly: true,
  },
  peer_turnover_interval: {
    key: 'peer_turnover_interval',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  request_queue_size: {
    key: 'request_queue_size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  dht_bootstrap_nodes: {
    key: 'dht_bootstrap_nodes',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_enabled: {
    key: 'i2p_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_address: {
    key: 'i2p_address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_port: {
    key: 'i2p_port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  i2p_mixed_mode: {
    key: 'i2p_mixed_mode',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_inbound_quantity: {
    key: 'i2p_inbound_quantity',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  i2p_outbound_quantity: {
    key: 'i2p_outbound_quantity',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  i2p_inbound_length: {
    key: 'i2p_inbound_length',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  i2p_outbound_length: {
    key: 'i2p_outbound_length',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  // ─── New fields ──────────────────────────────────────────
  torrent_content_layout: {
    key: 'torrent_content_layout',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  add_to_top_of_queue: {
    key: 'add_to_top_of_queue',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  torrent_stop_condition: {
    key: 'torrent_stop_condition',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  merge_trackers: {
    key: 'merge_trackers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  excluded_file_names_enabled: {
    key: 'excluded_file_names_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  excluded_file_names: {
    key: 'excluded_file_names',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  autorun_on_torrent_added_enabled: {
    key: 'autorun_on_torrent_added_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  autorun_on_torrent_added_program: {
    key: 'autorun_on_torrent_added_program',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  recheck_completed_torrents: {
    key: 'recheck_completed_torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  resolve_peer_countries: {
    key: 'resolve_peer_countries',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  reannounce_when_address_changed: {
    key: 'reannounce_when_address_changed',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  max_active_checking_torrents: {
    key: 'max_active_checking_torrents',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'bittorrent',
    min: 1,
    remoteOnly: true,
  },
  max_inactive_seeding_time_enabled: {
    key: 'max_inactive_seeding_time_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  max_inactive_seeding_time: {
    key: 'max_inactive_seeding_time',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'bittorrent',
    min: -1,
    remoteOnly: true,
  },
  resume_data_storage_type: {
    key: 'resume_data_storage_type',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  torrent_file_size_limit: {
    key: 'torrent_file_size_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: -1,
    remoteOnly: true,
  },
  save_resume_data_interval: {
    key: 'save_resume_data_interval',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  save_statistics_interval: {
    key: 'save_statistics_interval',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  confirm_torrent_recheck: {
    key: 'confirm_torrent_recheck',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  refresh_interval: {
    key: 'refresh_interval',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 500,
    remoteOnly: true,
  },
  customize_application_instance_name: {
    key: 'customize_application_instance_name',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  python_executable_path: {
    key: 'python_executable_path',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  torrent_content_removing_mode: {
    key: 'torrent_content_removing_mode',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  memory_working_set_limit: {
    key: 'memory_working_set_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  current_network_interface: {
    key: 'current_network_interface',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  current_ip_address: {
    key: 'current_ip_address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  disk_queue_size: {
    key: 'disk_queue_size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  disk_io_type: {
    key: 'disk_io_type',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  disk_io_read_mode: {
    key: 'disk_io_read_mode',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  disk_io_write_mode: {
    key: 'disk_io_write_mode',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  bdecode_depth_limit: {
    key: 'bdecode_depth_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  bdecode_token_limit: {
    key: 'bdecode_token_limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  socket_send_buffer_size: {
    key: 'socket_send_buffer_size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  socket_receive_buffer_size: {
    key: 'socket_receive_buffer_size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  announce_to_all_trackers_in_tier: {
    key: 'announce_to_all_trackers_in_tier',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  announce_port: {
    key: 'announce_port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 65535,
    remoteOnly: true,
  },
  add_trackers_url: {
    key: 'add_trackers_url',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  web_ui_reverse_proxy_enabled: {
    key: 'web_ui_reverse_proxy_enabled',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_reverse_proxies_list: {
    key: 'web_ui_reverse_proxies_list',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  ignore_ssl_errors: {
    key: 'ignore_ssl_errors',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  enable_port_forwarding_for_embedded_tracker: {
    key: 'enable_port_forwarding_for_embedded_tracker',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  use_subcategories: {
    key: 'use_subcategories',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  use_category_paths_in_manual_mode: {
    key: 'use_category_paths_in_manual_mode',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  delete_torrent_files_afterwards: {
    key: 'delete_torrent_files_afterwards',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
} as const;

export function getRemoteSettingMetadata<K extends PreferenceKey>(
  key: K
): RemoteSettingMetadata<K> {
  return REMOTE_SETTINGS_METADATA[key];
}

export function isRemoteOnlySetting(key: PreferenceKey): boolean {
  return REMOTE_SETTINGS_METADATA[key].remoteOnly;
}

export function validatePreferenceValue<K extends PreferenceKey>(
  key: K,
  value: unknown
): value is PreferenceValueType<K> {
  return REMOTE_SETTINGS_METADATA[key].validation(value);
}

export const DESKTOP_LOCAL_SETTINGS = [
  'minimize_to_tray',
  'close_to_tray',
  'start_minimized',
  'auto_start',
] as const;

export type DesktopLocalSetting = (typeof DESKTOP_LOCAL_SETTINGS)[number];

export function isDesktopLocalSetting(
  key: string
): key is DesktopLocalSetting {
  return (DESKTOP_LOCAL_SETTINGS as readonly string[]).includes(key);
}

export const MOBILE_ONLY_SETTINGS = [
  'theme_mode',
  'system_palette',
  'manual_palette',
  'manual_variant',
] as const;

export type MobileOnlySetting = (typeof MOBILE_ONLY_SETTINGS)[number];

export function isMobileOnlySetting(
  key: string
): key is MobileOnlySetting {
  return (MOBILE_ONLY_SETTINGS as readonly string[]).includes(key);
}
