import type { Preferences } from '../types/qbittorrent';

export type DesktopSection =
  | 'downloads'
  | 'connection'
  | 'speed'
  | 'bittorrent'
  | 'webui'
  | 'advanced'
  | 'general'
  | 'transfers'
  | 'network'
  | 'seeding'
  | 'privacy'
  | 'categories'
  | 'tags';

export type PreferenceKey = keyof Preferences;

export type PreferenceValueType<K extends PreferenceKey> = Preferences[K];

export type PreferenceValidator<K extends PreferenceKey> = (
  value: unknown
) => value is PreferenceValueType<K>;

export interface RemoteSettingMetadata<K extends PreferenceKey = PreferenceKey> {
  key: K;
  displayLabel: string;
  helpText: string;
  valueType: 'boolean' | 'number' | 'string' | 'record';
  validation: PreferenceValidator<K>;
  desktopSection: DesktopSection;
  min?: number;
  max?: number;
  options?: readonly { value: number; label: string }[];
  remoteOnly: boolean;
}

export const REMOTE_SETTINGS_METADATA: {
  [K in PreferenceKey]: RemoteSettingMetadata<K>;
} = {
  locale: {
    key: 'locale',
    displayLabel: 'Language',
    helpText: 'Application interface language',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  create_subfolder_enabled: {
    key: 'create_subfolder_enabled',
    displayLabel: 'Create Subfolder',
    helpText: 'Create a subfolder for multi-file torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  start_paused_enabled: {
    key: 'start_paused_enabled',
    displayLabel: 'Start Paused',
    helpText: 'Add torrents in paused state',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  auto_delete_mode: {
    key: 'auto_delete_mode',
    displayLabel: 'Auto Delete',
    helpText: 'Automatically delete torrents',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  preallocate_all: {
    key: 'preallocate_all',
    displayLabel: 'Preallocate Space',
    helpText: 'Preallocate disk space for files',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  incomplete_files_ext: {
    key: 'incomplete_files_ext',
    displayLabel: 'Incomplete Files Extension',
    helpText: 'Add .!ut extension to incomplete files',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  auto_tmm_enabled: {
    key: 'auto_tmm_enabled',
    displayLabel: 'Auto Torrent Management',
    helpText: 'Automatically manage torrent save paths',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  torrent_changed_tmm_enabled: {
    key: 'torrent_changed_tmm_enabled',
    displayLabel: 'Torrent Changed TMM',
    helpText: 'Move torrents when category changes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  save_path_changed_tmm_enabled: {
    key: 'save_path_changed_tmm_enabled',
    displayLabel: 'Save Path Changed TMM',
    helpText: 'Move torrents when default save path changes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  category_changed_tmm_enabled: {
    key: 'category_changed_tmm_enabled',
    displayLabel: 'Category Changed TMM',
    helpText: 'Move torrents when category save path changes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  save_path: {
    key: 'save_path',
    displayLabel: 'Default Save Path',
    helpText: 'Default folder for downloaded files',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  temp_path_enabled: {
    key: 'temp_path_enabled',
    displayLabel: 'Temp Path Enabled',
    helpText: 'Use a temporary folder for incomplete files',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  temp_path: {
    key: 'temp_path',
    displayLabel: 'Temp Path',
    helpText: 'Temporary folder for incomplete files',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  scan_dirs: {
    key: 'scan_dirs',
    displayLabel: 'Scan Dirs',
    helpText: 'Watch folders for new torrents',
    valueType: 'record',
    validation: (v): v is Record<string, number> => typeof v === 'object' && v !== null,
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  export_dir: {
    key: 'export_dir',
    displayLabel: 'Export Dir',
    helpText: 'Folder for exported torrents',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  export_dir_fin: {
    key: 'export_dir_fin',
    displayLabel: 'Export Dir Finished',
    helpText: 'Folder for completed torrents',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  mail_notification_enabled: {
    key: 'mail_notification_enabled',
    displayLabel: 'Email Notifications',
    helpText: 'Send email on torrent completion',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_sender: {
    key: 'mail_notification_sender',
    displayLabel: 'Email Sender',
    helpText: 'Sender email address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_email: {
    key: 'mail_notification_email',
    displayLabel: 'Notification Email',
    helpText: 'Email address for notifications',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_smtp: {
    key: 'mail_notification_smtp',
    displayLabel: 'SMTP Server',
    helpText: 'SMTP server for email',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_ssl_enabled: {
    key: 'mail_notification_ssl_enabled',
    displayLabel: 'Email SSL',
    helpText: 'Use SSL for email',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_auth_enabled: {
    key: 'mail_notification_auth_enabled',
    displayLabel: 'Email Auth',
    helpText: 'Use authentication for email',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_username: {
    key: 'mail_notification_username',
    displayLabel: 'Email Username',
    helpText: 'Username for email auth',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  mail_notification_password: {
    key: 'mail_notification_password',
    displayLabel: 'Email Password',
    helpText: 'Password for email auth',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  autorun_enabled: {
    key: 'autorun_enabled',
    displayLabel: 'Autorun Enabled',
    helpText: 'Run a command on torrent completion',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  autorun_program: {
    key: 'autorun_program',
    displayLabel: 'Autorun Program',
    helpText: 'Command to run on completion',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  queueing_enabled: {
    key: 'queueing_enabled',
    displayLabel: 'Queueing Enabled',
    helpText: 'Enable torrent queueing',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  max_active_downloads: {
    key: 'max_active_downloads',
    displayLabel: 'Max Active Downloads',
    helpText: 'Maximum number of active downloads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_active_torrents: {
    key: 'max_active_torrents',
    displayLabel: 'Max Active Torrents',
    helpText: 'Maximum number of active torrents',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_active_uploads: {
    key: 'max_active_uploads',
    displayLabel: 'Max Active Uploads',
    helpText: 'Maximum number of active uploads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  dont_count_slow_torrents: {
    key: 'dont_count_slow_torrents',
    displayLabel: 'Dont Count Slow Torrents',
    helpText: 'Dont count slow torrents in max active limits',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  slow_torrent_dl_rate_threshold: {
    key: 'slow_torrent_dl_rate_threshold',
    displayLabel: 'Slow Torrent Download Rate Threshold',
    helpText: 'Download rate threshold for slow torrent detection',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  slow_torrent_ul_rate_threshold: {
    key: 'slow_torrent_ul_rate_threshold',
    displayLabel: 'Slow Torrent Upload Rate Threshold',
    helpText: 'Upload rate threshold for slow torrent detection',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  slow_torrent_inactive_timer: {
    key: 'slow_torrent_inactive_timer',
    displayLabel: 'Slow Torrent Inactive Timer',
    helpText: 'Time before a torrent is considered slow (seconds)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_ratio_enabled: {
    key: 'max_ratio_enabled',
    displayLabel: 'Max Ratio Enabled',
    helpText: 'Stop seeding at maximum ratio',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'seeding',
    remoteOnly: true,
  },
  max_ratio: {
    key: 'max_ratio',
    displayLabel: 'Max Ratio',
    helpText: 'Maximum share ratio for seeding',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'seeding',
    min: 0,
    remoteOnly: true,
  },
  max_ratio_act: {
    key: 'max_ratio_act',
    displayLabel: 'Max Ratio Action',
    helpText: 'Action on max ratio: 0=pause, 1=stop, 2=remove',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'seeding',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  listen_port: {
    key: 'listen_port',
    displayLabel: 'Listening Port',
    helpText: 'Port for incoming connections (1-65535)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  upnp: {
    key: 'upnp',
    displayLabel: 'UPnP',
    helpText: 'Use UPnP to forward port',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  random_port: {
    key: 'random_port',
    displayLabel: 'Random Port',
    helpText: 'Use random port on startup',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  dl_limit: {
    key: 'dl_limit',
    displayLabel: 'Download Limit',
    helpText: 'Global download speed limit (0=unlimited)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  up_limit: {
    key: 'up_limit',
    displayLabel: 'Upload Limit',
    helpText: 'Global upload speed limit (0=unlimited)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  alt_dl_limit: {
    key: 'alt_dl_limit',
    displayLabel: 'Alternative Download Limit',
    helpText: 'Alternative download speed limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  alt_up_limit: {
    key: 'alt_up_limit',
    displayLabel: 'Alternative Upload Limit',
    helpText: 'Alternative upload speed limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    remoteOnly: true,
  },
  max_connec: {
    key: 'max_connec',
    displayLabel: 'Max Connections',
    helpText: 'Maximum number of connections',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  max_connec_per_torrent: {
    key: 'max_connec_per_torrent',
    displayLabel: 'Max Connections Per Torrent',
    helpText: 'Maximum connections per torrent',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  max_uploads: {
    key: 'max_uploads',
    displayLabel: 'Max Upload Slots',
    helpText: 'Maximum upload slots',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  max_uploads_per_torrent: {
    key: 'max_uploads_per_torrent',
    displayLabel: 'Max Uploads Per Torrent',
    helpText: 'Maximum upload slots per torrent',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  enable_piece_extent_affinity: {
    key: 'enable_piece_extent_affinity',
    displayLabel: 'Piece Extent Affinity',
    helpText: 'Prefer piece order for sequential downloads',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  bittorrent_protocol: {
    key: 'bittorrent_protocol',
    displayLabel: 'BitTorrent Protocol',
    helpText: '0=Both, 1=TCP, 2=uTP',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  limit_utp_rate: {
    key: 'limit_utp_rate',
    displayLabel: 'Limit uTP Rate',
    helpText: 'Include uTP in transfer limits',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  limit_tcp_overhead: {
    key: 'limit_tcp_overhead',
    displayLabel: 'TCP Overhead',
    helpText: 'Count TCP protocol overhead in limits',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  limit_lan_peers: {
    key: 'limit_lan_peers',
    displayLabel: 'LAN Peers',
    helpText: 'Apply speed limits to LAN peers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  scheduler_enabled: {
    key: 'scheduler_enabled',
    displayLabel: 'Scheduler',
    helpText: 'Enable scheduled speed limits',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  use_alt_speed_limits: {
    key: 'use_alt_speed_limits',
    displayLabel: 'Alternative Speed Limits',
    helpText: 'Use the configured alternative download and upload speed limits',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'transfers',
    remoteOnly: true,
  },
  schedule_from_hour: {
    key: 'schedule_from_hour',
    displayLabel: 'Schedule From Hour',
    helpText: 'Start hour for scheduled limits',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 23,
    remoteOnly: true,
  },
  schedule_from_min: {
    key: 'schedule_from_min',
    displayLabel: 'Schedule From Minute',
    helpText: 'Start minute for scheduled limits',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 59,
    remoteOnly: true,
  },
  schedule_to_hour: {
    key: 'schedule_to_hour',
    displayLabel: 'Schedule To Hour',
    helpText: 'End hour for scheduled limits',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 23,
    remoteOnly: true,
  },
  schedule_to_min: {
    key: 'schedule_to_min',
    displayLabel: 'Schedule To Minute',
    helpText: 'End minute for scheduled limits',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 59,
    remoteOnly: true,
  },
  scheduler_days: {
    key: 'scheduler_days',
    displayLabel: 'Scheduler Days',
    helpText: 'Days for scheduler (1-7)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'transfers',
    min: 0,
    max: 7,
    remoteOnly: true,
  },
  dht: {
    key: 'dht',
    displayLabel: 'DHT',
    helpText: 'Enable DHT (Distributed Hash Table)',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  pex: {
    key: 'pex',
    displayLabel: 'PeX',
    helpText: 'Enable Peer Exchange',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  lsd: {
    key: 'lsd',
    displayLabel: 'LSD',
    helpText: 'Enable Local Service Discovery',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  encryption: {
    key: 'encryption',
    displayLabel: 'Encryption',
    helpText: '0=Prefer, 1=Force, 2=Disable',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    max: 2,
    options: [
      { value: 0, label: 'Prefer' },
      { value: 1, label: 'Force' },
      { value: 2, label: 'Disable' },
    ] as const,
    remoteOnly: true,
  },
  anonymous_mode: {
    key: 'anonymous_mode',
    displayLabel: 'Anonymous Mode',
    helpText: 'Hide sensitive information from trackers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  proxy_type: {
    key: 'proxy_type',
    displayLabel: 'Proxy Type',
    helpText: 'Proxy connection type',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'connection',
    min: 0,
    max: 6,
    remoteOnly: true,
  },
  proxy_ip: {
    key: 'proxy_ip',
    displayLabel: 'Proxy IP',
    helpText: 'Proxy server IP address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_port: {
    key: 'proxy_port',
    displayLabel: 'Proxy Port',
    helpText: 'Proxy server port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'connection',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  proxy_peer_connections: {
    key: 'proxy_peer_connections',
    displayLabel: 'Proxy Peer Connections',
    helpText: 'Use proxy for peer connections',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_auth_enabled: {
    key: 'proxy_auth_enabled',
    displayLabel: 'Proxy Auth',
    helpText: 'Use authentication for proxy',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_username: {
    key: 'proxy_username',
    displayLabel: 'Proxy Username',
    helpText: 'Username for proxy authentication',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_password: {
    key: 'proxy_password',
    displayLabel: 'Proxy Password',
    helpText: 'Password for proxy authentication',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  proxy_torrents_only: {
    key: 'proxy_torrents_only',
    displayLabel: 'Proxy Torrents Only',
    helpText: 'Only use proxy for torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'connection',
    remoteOnly: true,
  },
  ip_filter_enabled: {
    key: 'ip_filter_enabled',
    displayLabel: 'IP Filter',
    helpText: 'Enable IP filter',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  ip_filter_path: {
    key: 'ip_filter_path',
    displayLabel: 'IP Filter Path',
    helpText: 'Path to IP filter file',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  ip_filter_trackers: {
    key: 'ip_filter_trackers',
    displayLabel: 'IP Filter Trackers',
    helpText: 'Apply IP filter to trackers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'privacy',
    remoteOnly: true,
  },
  web_ui_domain_list: {
    key: 'web_ui_domain_list',
    displayLabel: 'WebUI Domain List',
    helpText: 'Allowed domains for WebUI',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_address: {
    key: 'web_ui_address',
    displayLabel: 'WebUI Address',
    helpText: 'WebUI listening address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_port: {
    key: 'web_ui_port',
    displayLabel: 'WebUI Port',
    helpText: 'WebUI listening port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  web_ui_upnp: {
    key: 'web_ui_upnp',
    displayLabel: 'WebUI UPnP',
    helpText: 'Use UPnP to forward WebUI port',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_username: {
    key: 'web_ui_username',
    displayLabel: 'WebUI Username',
    helpText: 'WebUI login username',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_password: {
    key: 'web_ui_password',
    displayLabel: 'WebUI Password',
    helpText: 'WebUI login password',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_csrf_protection_enabled: {
    key: 'web_ui_csrf_protection_enabled',
    displayLabel: 'CSRF Protection',
    helpText: 'Enable CSRF protection',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_clickjacking_protection_enabled: {
    key: 'web_ui_clickjacking_protection_enabled',
    displayLabel: 'Clickjacking Protection',
    helpText: 'Enable clickjacking protection',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_secure_cookie_enabled: {
    key: 'web_ui_secure_cookie_enabled',
    displayLabel: 'Secure Cookie',
    helpText: 'Use secure flag for cookies',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_max_auth_fail_count: {
    key: 'web_ui_max_auth_fail_count',
    displayLabel: 'Max Auth Failures',
    helpText: 'Maximum authentication failures before ban',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 1,
    remoteOnly: true,
  },
  web_ui_ban_duration: {
    key: 'web_ui_ban_duration',
    displayLabel: 'Ban Duration',
    helpText: 'IP ban duration in seconds',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 0,
    remoteOnly: true,
  },
  web_ui_session_timeout: {
    key: 'web_ui_session_timeout',
    displayLabel: 'Session Timeout',
    helpText: 'Session timeout in seconds',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'webui',
    min: 0,
    remoteOnly: true,
  },
  web_ui_host_header_validation_enabled: {
    key: 'web_ui_host_header_validation_enabled',
    displayLabel: 'Host Header Validation',
    helpText: 'Validate host header',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  bypass_local_auth: {
    key: 'bypass_local_auth',
    displayLabel: 'Local Auth Bypass',
    helpText: 'Skip authentication for localhost',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  bypass_auth_subnet_whitelist_enabled: {
    key: 'bypass_auth_subnet_whitelist_enabled',
    displayLabel: 'Subnet Whitelist',
    helpText: 'Enable subnet whitelist for auth bypass',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  bypass_auth_subnet_whitelist: {
    key: 'bypass_auth_subnet_whitelist',
    displayLabel: 'Subnet Whitelist',
    helpText: 'Comma-separated list of allowed subnets',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  alternative_webui_enabled: {
    key: 'alternative_webui_enabled',
    displayLabel: 'Alternative WebUI',
    helpText: 'Enable alternative WebUI folder',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  alternative_webui_path: {
    key: 'alternative_webui_path',
    displayLabel: 'Alternative WebUI Path',
    helpText: 'Path to alternative WebUI files',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  use_https: {
    key: 'use_https',
    displayLabel: 'HTTPS',
    helpText: 'Enable HTTPS for WebUI',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  ssl_key: {
    key: 'ssl_key',
    displayLabel: 'SSL Key',
    helpText: 'SSL private key',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  ssl_cert: {
    key: 'ssl_cert',
    displayLabel: 'SSL Certificate',
    helpText: 'SSL certificate',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_https_key: {
    key: 'web_ui_https_key',
    displayLabel: 'WebUI HTTPS Key',
    helpText: 'WebUI HTTPS private key',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_https_cert: {
    key: 'web_ui_https_cert',
    displayLabel: 'WebUI HTTPS Cert',
    helpText: 'WebUI HTTPS certificate',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  dyndns_enabled: {
    key: 'dyndns_enabled',
    displayLabel: 'DynDNS',
    helpText: 'Enable Dynamic DNS',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  dyndns_service: {
    key: 'dyndns_service',
    displayLabel: 'DynDNS Service',
    helpText: 'Dynamic DNS service provider',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'general',
    min: 0,
    max: 3,
    remoteOnly: true,
  },
  dyndns_username: {
    key: 'dyndns_username',
    displayLabel: 'DynDNS Username',
    helpText: 'DynDNS account username',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  dyndns_password: {
    key: 'dyndns_password',
    displayLabel: 'DynDNS Password',
    helpText: 'DynDNS account password',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  dyndns_domain: {
    key: 'dyndns_domain',
    displayLabel: 'DynDNS Domain',
    helpText: 'DynDNS domain name',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_refresh_interval: {
    key: 'rss_refresh_interval',
    displayLabel: 'RSS Refresh Interval',
    helpText: 'RSS feed refresh interval in minutes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'general',
    min: 0,
    remoteOnly: true,
  },
  rss_max_articles_per_feed: {
    key: 'rss_max_articles_per_feed',
    displayLabel: 'RSS Max Articles',
    helpText: 'Maximum articles per RSS feed',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'general',
    min: 0,
    remoteOnly: true,
  },
  rss_processing_enabled: {
    key: 'rss_processing_enabled',
    displayLabel: 'RSS Processing',
    helpText: 'Enable RSS article processing',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_auto_downloading_enabled: {
    key: 'rss_auto_downloading_enabled',
    displayLabel: 'RSS Auto Downloading',
    helpText: 'Enable automatic RSS downloads',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_download_repack_proper_episodes: {
    key: 'rss_download_repack_proper_episodes',
    displayLabel: 'RSS Repack Episodes',
    helpText: 'Download repack episodes',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  rss_smart_episode_filters: {
    key: 'rss_smart_episode_filters',
    displayLabel: 'RSS Smart Filters',
    helpText: 'Smart episode filter strings',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  add_trackers_enabled: {
    key: 'add_trackers_enabled',
    displayLabel: 'Add Trackers',
    helpText: 'Auto-add trackers to new torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  add_trackers: {
    key: 'add_trackers',
    displayLabel: 'Tracker List',
    helpText: 'Trackers to auto-add',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  web_ui_use_custom_http_headers_enabled: {
    key: 'web_ui_use_custom_http_headers_enabled',
    displayLabel: 'Custom HTTP Headers',
    helpText: 'Use custom HTTP headers in WebUI',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'general',
    remoteOnly: true,
  },
  web_ui_custom_http_headers: {
    key: 'web_ui_custom_http_headers',
    displayLabel: 'Custom HTTP Headers',
    helpText: 'Custom HTTP headers',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'general',
    remoteOnly: true,
  },
  max_seeding_time_enabled: {
    key: 'max_seeding_time_enabled',
    displayLabel: 'Max Seeding Time',
    helpText: 'Limit maximum seeding time',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'seeding',
    remoteOnly: true,
  },
  max_seeding_time: {
    key: 'max_seeding_time',
    displayLabel: 'Max Seeding Time',
    helpText: 'Maximum seeding time in minutes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'seeding',
    min: 0,
    remoteOnly: true,
  },
  announce_to_all_tiers: {
    key: 'announce_to_all_tiers',
    displayLabel: 'Announce All Tiers',
    helpText: 'Announce to all tracker tiers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  announce_to_all_trackers: {
    key: 'announce_to_all_trackers',
    displayLabel: 'Announce All Trackers',
    helpText: 'Announce to all trackers in tier',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  async_io_threads: {
    key: 'async_io_threads',
    displayLabel: 'Async IO Threads',
    helpText: 'Number of async IO threads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    max: 32,
    remoteOnly: true,
  },
  hashing_threads: {
    key: 'hashing_threads',
    displayLabel: 'Hashing Threads',
    helpText: 'Number of hashing threads',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    max: 64,
    remoteOnly: true,
  },
  file_pool_size: {
    key: 'file_pool_size',
    displayLabel: 'File Pool Size',
    helpText: 'File pool size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  checking_memory_use: {
    key: 'checking_memory_use',
    displayLabel: 'Checking Memory',
    helpText: 'Memory to use for checking (MB)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  disk_cache: {
    key: 'disk_cache',
    displayLabel: 'Disk Cache',
    helpText: 'Disk cache size in MB',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  disk_cache_ttl: {
    key: 'disk_cache_ttl',
    displayLabel: 'Disk Cache TTL',
    helpText: 'Disk cache TTL in seconds',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  enable_upload_suggestions: {
    key: 'enable_upload_suggestions',
    displayLabel: 'Upload Suggestions',
    helpText: 'Suggest upload pieces to peers',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  upload_suggestions_interval: {
    key: 'upload_suggestions_interval',
    displayLabel: 'Upload Suggestions Interval',
    helpText: 'Interval for upload suggestions (ms)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  send_buffer_watermark: {
    key: 'send_buffer_watermark',
    displayLabel: 'Send Buffer Watermark',
    helpText: 'Send buffer watermark',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  send_buffer_low_watermark: {
    key: 'send_buffer_low_watermark',
    displayLabel: 'Send Buffer Low Watermark',
    helpText: 'Send buffer low watermark',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  send_buffer_watermark_factor: {
    key: 'send_buffer_watermark_factor',
    displayLabel: 'Send Buffer Watermark Factor',
    helpText: 'Send buffer watermark factor',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  connection_speed: {
    key: 'connection_speed',
    displayLabel: 'Connection Speed',
    helpText: 'Outgoing connections per second',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  socket_backlog_size: {
    key: 'socket_backlog_size',
    displayLabel: 'Socket Backlog Size',
    helpText: 'Socket backlog size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  outgoing_ports_min: {
    key: 'outgoing_ports_min',
    displayLabel: 'Outgoing Port Min',
    helpText: 'Minimum outgoing port (0=any)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    max: 65535,
    remoteOnly: true,
  },
  outgoing_ports_max: {
    key: 'outgoing_ports_max',
    displayLabel: 'Outgoing Port Max',
    helpText: 'Maximum outgoing port (0=any)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    max: 65535,
    remoteOnly: true,
  },
  upnp_lease_duration: {
    key: 'upnp_lease_duration',
    displayLabel: 'UPnP Lease Duration',
    helpText: 'UPnP lease duration in seconds',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  peer_tos: {
    key: 'peer_tos',
    displayLabel: 'Peer TOS',
    helpText: 'Peer Type of Service',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 6,
    remoteOnly: true,
  },
  utp_tcp_mixed_mode: {
    key: 'utp_tcp_mixed_mode',
    displayLabel: 'uTP TCP Mixed Mode',
    helpText: '0=Disabled, 1=Prefer, 2=Force',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  idn_support_enabled: {
    key: 'idn_support_enabled',
    displayLabel: 'IDN Support',
    helpText: 'Support internationalized domain names',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  enable_multi_connections_from_same_ip: {
    key: 'enable_multi_connections_from_same_ip',
    displayLabel: 'Multi Connections Same IP',
    helpText: 'Allow multiple connections from same IP',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  validate_https_tracker_certificate: {
    key: 'validate_https_tracker_certificate',
    displayLabel: 'Validate Tracker Cert',
    helpText: 'Validate HTTPS tracker certificates',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  ssrf_mitigation: {
    key: 'ssrf_mitigation',
    displayLabel: 'SSRF Mitigation',
    helpText: 'Enable SSRF mitigation',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  block_peers_on_privileged_ports: {
    key: 'block_peers_on_privileged_ports',
    displayLabel: 'Block Privileged Ports',
    helpText: 'Block peers on privileged ports',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  enable_embedded_tracker: {
    key: 'enable_embedded_tracker',
    displayLabel: 'Embedded Tracker',
    helpText: 'Enable embedded tracker',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  embedded_tracker_port: {
    key: 'embedded_tracker_port',
    displayLabel: 'Embedded Tracker Port',
    helpText: 'Embedded tracker listening port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  mark_of_the_web: {
    key: 'mark_of_the_web',
    displayLabel: 'Mark of the Web',
    helpText: 'Add MOTW to downloaded files',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  upload_slots_behavior: {
    key: 'upload_slots_behavior',
    displayLabel: 'Upload Slots Behavior',
    helpText: 'Upload slots behavior',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  upload_choking_algorithm: {
    key: 'upload_choking_algorithm',
    displayLabel: 'Upload Choking Algorithm',
    helpText: 'Upload choking algorithm',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 2,
    remoteOnly: true,
  },
  announce_ip: {
    key: 'announce_ip',
    displayLabel: 'Announce IP',
    helpText: 'IP to announce to trackers',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  max_concurrent_http_announces: {
    key: 'max_concurrent_http_announces',
    displayLabel: 'Max Concurrent HTTP Announces',
    helpText: 'Maximum concurrent HTTP announces',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  stop_tracker_timeout: {
    key: 'stop_tracker_timeout',
    displayLabel: 'Stop Tracker Timeout',
    helpText: 'Stop tracker timeout in seconds',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  peer_turnover: {
    key: 'peer_turnover',
    displayLabel: 'Peer Turnover',
    helpText: 'Peer turnover percentage',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 100,
    remoteOnly: true,
  },
  peer_turnover_cutoff: {
    key: 'peer_turnover_cutoff',
    displayLabel: 'Peer Turnover Cutoff',
    helpText: 'Peer turnover cutoff percentage',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 100,
    remoteOnly: true,
  },
  peer_turnover_interval: {
    key: 'peer_turnover_interval',
    displayLabel: 'Peer Turnover Interval',
    helpText: 'Peer turnover interval in seconds',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  request_queue_size: {
    key: 'request_queue_size',
    displayLabel: 'Request Queue Size',
    helpText: 'Request queue size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  dht_bootstrap_nodes: {
    key: 'dht_bootstrap_nodes',
    displayLabel: 'DHT Bootstrap Nodes',
    helpText: 'Comma-separated list of DHT bootstrap nodes',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_enabled: {
    key: 'i2p_enabled',
    displayLabel: 'I2P',
    helpText: 'Enable I2P network',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_address: {
    key: 'i2p_address',
    displayLabel: 'I2P Address',
    helpText: 'I2P SAM bridge address',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_port: {
    key: 'i2p_port',
    displayLabel: 'I2P Port',
    helpText: 'I2P SAM bridge port',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 1,
    max: 65535,
    remoteOnly: true,
  },
  i2p_mixed_mode: {
    key: 'i2p_mixed_mode',
    displayLabel: 'I2P Mixed Mode',
    helpText: 'I2P mixed mode',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'network',
    remoteOnly: true,
  },
  i2p_inbound_quantity: {
    key: 'i2p_inbound_quantity',
    displayLabel: 'I2P Inbound Quantity',
    helpText: 'I2P inbound quantity',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  i2p_outbound_quantity: {
    key: 'i2p_outbound_quantity',
    displayLabel: 'I2P Outbound Quantity',
    helpText: 'I2P outbound quantity',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  i2p_inbound_length: {
    key: 'i2p_inbound_length',
    displayLabel: 'I2P Inbound Length',
    helpText: 'I2P inbound length',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  i2p_outbound_length: {
    key: 'i2p_outbound_length',
    displayLabel: 'I2P Outbound Length',
    helpText: 'I2P outbound length',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'network',
    min: 0,
    remoteOnly: true,
  },
  // ─── New fields ──────────────────────────────────────────
  torrent_content_layout: {
    key: 'torrent_content_layout',
    displayLabel: 'Torrent Content Layout',
    helpText: 'Content layout when adding torrents',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  add_to_top_of_queue: {
    key: 'add_to_top_of_queue',
    displayLabel: 'Add to Top of Queue',
    helpText: 'Add new torrents to the top of the queue',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  torrent_stop_condition: {
    key: 'torrent_stop_condition',
    displayLabel: 'Torrent Stop Condition',
    helpText: 'Condition to stop a torrent after metadata received',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  merge_trackers: {
    key: 'merge_trackers',
    displayLabel: 'Merge Trackers',
    helpText: 'Merge trackers from duplicate torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  excluded_file_names_enabled: {
    key: 'excluded_file_names_enabled',
    displayLabel: 'Excluded File Names Enabled',
    helpText: 'Enable excluding files by name pattern',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  excluded_file_names: {
    key: 'excluded_file_names',
    displayLabel: 'Excluded File Names',
    helpText: 'File name patterns to exclude',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  autorun_on_torrent_added_enabled: {
    key: 'autorun_on_torrent_added_enabled',
    displayLabel: 'Auto-Run on Torrent Added',
    helpText: 'Run a program when a torrent is added',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  autorun_on_torrent_added_program: {
    key: 'autorun_on_torrent_added_program',
    displayLabel: 'Auto-Run Program (Added)',
    helpText: 'Program to run when a torrent is added',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  recheck_completed_torrents: {
    key: 'recheck_completed_torrents',
    displayLabel: 'Recheck Completed Torrents',
    helpText: 'Recheck torrents on completion',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  resolve_peer_countries: {
    key: 'resolve_peer_countries',
    displayLabel: 'Resolve Peer Countries',
    helpText: 'Resolve peer IP addresses to countries',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  reannounce_when_address_changed: {
    key: 'reannounce_when_address_changed',
    displayLabel: 'Reannounce When Address Changed',
    helpText: 'Reannounce to all trackers when IP changes',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  max_active_checking_torrents: {
    key: 'max_active_checking_torrents',
    displayLabel: 'Max Active Checking Torrents',
    helpText: 'Maximum number of simultaneous checking torrents',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'bittorrent',
    min: 1,
    remoteOnly: true,
  },
  max_inactive_seeding_time_enabled: {
    key: 'max_inactive_seeding_time_enabled',
    displayLabel: 'Max Inactive Seeding Time Enabled',
    helpText: 'Enable limit on inactive seeding time',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  max_inactive_seeding_time: {
    key: 'max_inactive_seeding_time',
    displayLabel: 'Max Inactive Seeding Time',
    helpText: 'Maximum inactive seeding time in minutes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'bittorrent',
    min: -1,
    remoteOnly: true,
  },
  resume_data_storage_type: {
    key: 'resume_data_storage_type',
    displayLabel: 'Resume Data Storage Type',
    helpText: 'Type of storage for resume data',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  torrent_file_size_limit: {
    key: 'torrent_file_size_limit',
    displayLabel: 'Torrent File Size Limit',
    helpText: 'Maximum torrent file size',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: -1,
    remoteOnly: true,
  },
  save_resume_data_interval: {
    key: 'save_resume_data_interval',
    displayLabel: 'Save Resume Data Interval',
    helpText: 'Interval in minutes for saving resume data',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  save_statistics_interval: {
    key: 'save_statistics_interval',
    displayLabel: 'Save Statistics Interval',
    helpText: 'Interval in minutes for saving statistics',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  confirm_torrent_recheck: {
    key: 'confirm_torrent_recheck',
    displayLabel: 'Confirm Torrent Recheck',
    helpText: 'Confirm before rechecking torrents',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  refresh_interval: {
    key: 'refresh_interval',
    displayLabel: 'Refresh Interval',
    helpText: 'Refresh interval for the transfer list (ms)',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 500,
    remoteOnly: true,
  },
  customize_application_instance_name: {
    key: 'customize_application_instance_name',
    displayLabel: 'Application Instance Name',
    helpText: 'Custom application instance name',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  python_executable_path: {
    key: 'python_executable_path',
    displayLabel: 'Python Executable Path',
    helpText: 'Path to the Python executable for search plugins',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  torrent_content_removing_mode: {
    key: 'torrent_content_removing_mode',
    displayLabel: 'Torrent Content Removing Mode',
    helpText: 'How to remove torrent content files',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  memory_working_set_limit: {
    key: 'memory_working_set_limit',
    displayLabel: 'Memory Working Set Limit',
    helpText: 'Physical memory (RAM) usage limit in MiB',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 1,
    remoteOnly: true,
  },
  current_network_interface: {
    key: 'current_network_interface',
    displayLabel: 'Network Interface',
    helpText: 'Network interface to use',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  current_ip_address: {
    key: 'current_ip_address',
    displayLabel: 'IP Address',
    helpText: 'Optional IP address to bind to',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  disk_queue_size: {
    key: 'disk_queue_size',
    displayLabel: 'Disk Queue Size',
    helpText: 'Disk queue size in bytes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  disk_io_type: {
    key: 'disk_io_type',
    displayLabel: 'Disk IO Type',
    helpText: 'Disk IO type',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  disk_io_read_mode: {
    key: 'disk_io_read_mode',
    displayLabel: 'Disk IO Read Mode',
    helpText: 'Disk IO read mode',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  disk_io_write_mode: {
    key: 'disk_io_write_mode',
    displayLabel: 'Disk IO Write Mode',
    helpText: 'Disk IO write mode',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  bdecode_depth_limit: {
    key: 'bdecode_depth_limit',
    displayLabel: 'Bdecode Depth Limit',
    helpText: 'Bdecode depth limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  bdecode_token_limit: {
    key: 'bdecode_token_limit',
    displayLabel: 'Bdecode Token Limit',
    helpText: 'Bdecode token limit',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  socket_send_buffer_size: {
    key: 'socket_send_buffer_size',
    displayLabel: 'Socket Send Buffer Size',
    helpText: 'Socket send buffer size in bytes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  socket_receive_buffer_size: {
    key: 'socket_receive_buffer_size',
    displayLabel: 'Socket Receive Buffer Size',
    helpText: 'Socket receive buffer size in bytes',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    remoteOnly: true,
  },
  announce_to_all_trackers_in_tier: {
    key: 'announce_to_all_trackers_in_tier',
    displayLabel: 'Announce to All Trackers in Tier',
    helpText: 'Announce to all trackers in a tier',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  announce_port: {
    key: 'announce_port',
    displayLabel: 'Announce Port',
    helpText: 'Port to announce to trackers',
    valueType: 'number',
    validation: (v): v is number => typeof v === 'number',
    desktopSection: 'advanced',
    min: 0,
    max: 65535,
    remoteOnly: true,
  },
  add_trackers_url: {
    key: 'add_trackers_url',
    displayLabel: 'Additional Trackers URL',
    helpText: 'URLs for additional trackers to add to new torrents',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'bittorrent',
    remoteOnly: true,
  },
  web_ui_reverse_proxy_enabled: {
    key: 'web_ui_reverse_proxy_enabled',
    displayLabel: 'Reverse Proxy Enabled',
    helpText: 'Enable reverse proxy support for WebUI',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  web_ui_reverse_proxies_list: {
    key: 'web_ui_reverse_proxies_list',
    displayLabel: 'Reverse Proxies List',
    helpText: 'Trusted reverse proxy addresses',
    valueType: 'string',
    validation: (v): v is string => typeof v === 'string',
    desktopSection: 'webui',
    remoteOnly: true,
  },
  ignore_ssl_errors: {
    key: 'ignore_ssl_errors',
    displayLabel: 'Ignore SSL Errors',
    helpText: 'Ignore SSL errors for tracker connections',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  enable_port_forwarding_for_embedded_tracker: {
    key: 'enable_port_forwarding_for_embedded_tracker',
    displayLabel: 'Port Forwarding for Embedded Tracker',
    helpText: 'Enable port forwarding for the embedded tracker',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'advanced',
    remoteOnly: true,
  },
  use_subcategories: {
    key: 'use_subcategories',
    displayLabel: 'Use Subcategories',
    helpText: 'Enable subcategory support',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  use_category_paths_in_manual_mode: {
    key: 'use_category_paths_in_manual_mode',
    displayLabel: 'Category Paths in Manual Mode',
    helpText: 'Use category paths in manual mode',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
  delete_torrent_files_afterwards: {
    key: 'delete_torrent_files_afterwards',
    displayLabel: 'Delete .torrent Files Afterwards',
    helpText: 'Delete .torrent files after adding',
    valueType: 'boolean',
    validation: (v): v is boolean => typeof v === 'boolean',
    desktopSection: 'downloads',
    remoteOnly: true,
  },
} as const;

export function getRemoteSettingMetadata<K extends PreferenceKey>(
  key: K
): RemoteSettingMetadata<K> {
  return REMOTE_SETTINGS_METADATA[key];
}

export function isRemoteOnlySetting(key: PreferenceKey): boolean {
  return REMOTE_SETTINGS_METADATA[key].remoteOnly;
}

export function validatePreferenceValue<K extends PreferenceKey>(
  key: K,
  value: unknown
): value is PreferenceValueType<K> {
  return REMOTE_SETTINGS_METADATA[key].validation(value);
}

export const DESKTOP_LOCAL_SETTINGS = [
  'minimize_to_tray',
  'close_to_tray',
  'start_minimized',
  'auto_start',
] as const;

export type DesktopLocalSetting = (typeof DESKTOP_LOCAL_SETTINGS)[number];

export function isDesktopLocalSetting(
  key: string
): key is DesktopLocalSetting {
  return (DESKTOP_LOCAL_SETTINGS as readonly string[]).includes(key);
}

export const MOBILE_ONLY_SETTINGS = [
  'theme_mode',
  'system_palette',
  'manual_palette',
  'manual_variant',
] as const;

export type MobileOnlySetting = (typeof MOBILE_ONLY_SETTINGS)[number];

export function isMobileOnlySetting(
  key: string
): key is MobileOnlySetting {
  return (MOBILE_ONLY_SETTINGS as readonly string[]).includes(key);
}
