//! Shared server domain types for Phase 3.
//!
//! These types are the safe, renderer-facing DTOs for server management.
//! Internal Rust storage may hold credentials; these DTOs do not expose passwords.

use serde::{Deserialize, Serialize};

/// Credential persistence status reported to the frontend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CredentialStatus {
    /// Password was saved to persistent secure storage (keychain).
    Stored,
    /// Password is held only in transient in-memory map for the current process.
    SessionOnly,
    /// No password is available (user never provided one or it was cleared).
    Missing,
    /// Secure storage was unavailable or failed; password not persisted.
    Unavailable,
    /// Frontend did not request password persistence.
    NotRequested,
    /// Initial state before any credential operation has occurred.
    Unknown,
}

/// Password-free summary of a saved server, used for listing and selecting.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SavedServerSummary {
    pub id: String,
    pub name: String,
    pub url: String,
    pub username: String,
    /// Current credential persistence status.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential_status: Option<CredentialStatus>,
    /// Human-readable warning when credential storage had a partial failure.
    /// This is safe to display to the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential_warning: Option<String>,
}

/// Password-free summary of the currently active server in the session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveServerSummary {
    pub id: String,
    pub name: String,
    pub url: String,
    pub username: String,
}

/// Mapping from a server-side path prefix to a local path prefix.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathMapping {
    #[serde(rename = "serverPath", alias = "server_path")]
    pub server_path: String,
    #[serde(rename = "localPath", alias = "local_path")]
    pub local_path: String,
}

/// Input for credentials when adding or testing a server connection.
/// This is passed from renderer -> Rust for add/test flows only.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerCredentialsInput {
    pub username: String,
    pub password: String,
}

/// Internal storage record for a server with credentials.
/// This lives in the Rust-owned store and is NOT exposed to the renderer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerRecord {
    pub id: String,
    pub name: String,
    pub url: String,
    pub username: String,
    /// Hashed or zeroized — stored only for session re-use, never serialized to disk.
    #[serde(skip)]
    pub password: String,
}

impl ServerRecord {
    pub fn into_summary(
        self,
        credential_status: Option<CredentialStatus>,
        credential_warning: Option<String>,
    ) -> SavedServerSummary {
        SavedServerSummary {
            id: self.id,
            name: self.name,
            url: self.url,
            username: self.username,
            credential_status,
            credential_warning,
        }
    }

    pub fn as_summary(
        &self,
        credential_status: Option<CredentialStatus>,
        credential_warning: Option<String>,
    ) -> SavedServerSummary {
        SavedServerSummary {
            id: self.id.clone(),
            name: self.name.clone(),
            url: self.url.clone(),
            username: self.username.clone(),
            credential_status,
            credential_warning,
        }
    }
}

/// Input for adding a new server.
/// ID is generated by Rust repository code, not provided by renderer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddServerInput {
    pub name: String,
    pub url: String,
    pub username: String,
    pub password: String,
    /// Whether to persist the password in secure storage.
    /// Defaults to true when omitted.
    #[serde(default = "default_remember_password")]
    pub remember_password: bool,
}

fn default_remember_password() -> bool {
    true
}

/// Input for updating an existing server (partial update allowed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateServerInput {
    pub id: String,
    pub name: Option<String>,
    pub url: Option<String>,
    pub username: Option<String>,
    pub password: Option<String>,
    /// Whether to persist the password in secure storage.
    /// - None: do not change current setting
    /// - Some(true): store password securely; if storage fails, keep in transient map
    /// - Some(false): remove from secure storage; keep only in transient map for session
    #[serde(default = "default_remember_password_option")]
    pub remember_password: Option<bool>,
}

fn default_remember_password_option() -> Option<bool> {
    None
}

/// Response when testing a server connection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestConnectionResult {
    pub success: bool,
    pub error: Option<String>,
}

/// Input for normalizing a server URL.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NormalizeServerUrlInput {
    pub url: String,
    #[serde(default = "default_https_scheme")]
    pub default_scheme: String,
}

/// Output from normalizing a server URL.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormalizeServerUrlOutput {
    pub normalized: String,
}

/// Result of probing a server URL to determine its scheme and reachability.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProbeServerSchemeResult {
    pub success: bool,
    pub normalized_url: Option<String>,
    pub error: Option<String>,
}

/// Result of validating a server URL format and structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerValidationResult {
    pub valid: bool,
    pub errors: Vec<String>,
}

fn default_https_scheme() -> String {
    "https://".to_string()
}
